#!/bin/sh
# postinst script for opengalaxy-common

set -e

case "$1" in
    configure)

    # Users in group 'staff' may write to the openGalaxy shared data directory
    chown root:staff /usr/share/galaxy
	  chmod u-s,u+rwx,g+rwx,g-s,o+rx,o-w /usr/share/galaxy

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
