#!/bin/sh
# postinst script for opengalaxy-certificates-manager

set -e

case "$1" in
    configure)

    chown root:staff /var/log/galaxy
    chmod g+w /var/log/galaxy

    if test -x /usr/bin/update-menus; then update-menus; fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
